version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: sicc-postgres
    restart: always
    environment:
      POSTGRES_USER: sicc
      POSTGRES_PASSWORD: sicc
      POSTGRES_DB: siccdb
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sicc -d siccdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: nicolaspa23/sicc-api-image:latest
    container_name: sicc-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/siccdb
      SPRING_DATASOURCE_USERNAME: sicc
      SPRING_DATASOURCE_PASSWORD: sicc
      # SPRING_PROFILES_ACTIVE: prod   # si usas perfiles

  frontend:
    image: nicolaspa23/sicc-frontend-image:latest
    container_name: sicc-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  pgdata:

